baseURL = 'https://ivopc.github.io/'
languageCode = 'pt-BR'
theme = "portifa"

defaultContentLanguage = 'br'
defaultContentLanguageInSubdir = false
[languages]
  [languages.br]
    contentDir = 'content/br'
    disabled = false
    languageCode = 'pt-BR'
    languageDirection = 'ltr'
    languageName = 'Portugues Brasil'
    title = 'Ivo Camargo - Desenvolvedor Web e Desenvolvedor de Jogos'
    weight = 3
    [languages.br.params]
      subtitle = 'Programador, desenvolvedor de sites e jogos freelancer'
  [languages.en]
    contentDir = 'content/en'
    disabled = false
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'English'
    title = 'Ivo Camargo - Web Developer and Game Developer'
    weight = 2
    [languages.en.params]
      subtitle = 'Programmer, web and game developer freelance'

[markup.goldmark.renderer]
  unsafe = true