baseURL = 'https://ivopc.github.io/blog/'
languageCode = 'en-US'
title = 'Ivopc Blog'
theme = 'ananke'


[deployment]

[[deployment.targets]]
# An arbitrary name for this target.
name = "production"

# URL specifies the Go Cloud Development Kit URL to deploy to. Examples:
URL = "https://ivopc.github.io/blog/"