baseURL = 'https://ivopc.github.io/blog'
title = 'Ivopc Blog'
author = "Ivopc"
copyright = "Ivopc"
paginate = 3
languageCode = 'en'
defaultContentLanguage = "en"
hasCJKLanguage = true
enableInlineShortcodes = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]
enableRobotsTXT = true
enableEmoji = true

[params]
  # dir name of your blog content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "content/post"

[markup]
[markup.highlight]
  # lineNos = true
  noClasses = false
[markup.goldmark]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.goldmark.extensions]
    [markup.goldmark.extensions.cjk]
      enable = true
      eastAsianLineBreaks = true
      escapedSpace = true

[privacy]
  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[module]
  [module.hugoVersion]
    extended = false
    min = "0.120.0"

[menu]

  [[menu.main]]
    identifier = "post"
    name = "Post"
    pageRef = "/post"
    weight = 0